name: view_model_kit
description: A simple and easy ViewModel and state management Library. support ViewModel's state hold, Global state management. (Container's state hold)
version: 0.2.0
homepage: https://github.com/note11g/view_model_kit

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
