name: view_model_kit
description: A simple and easy ViewModel and state management Library.
version: 0.0.2
homepage: https://github.com/note11g/view_model_kit

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
